import { Howl } from 'howler';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import AudioCard from '../components/AudioCard';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const hello = new Howl({
    src: ['hello.mp3'],
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AudioCard text="hello" altText="hello" audioFile="hello.mp3" />
    </div>
  );
};

export default Home;
